[package]
name = "rand_pass"
version = "0.1.0"
authors = ["Imed Adel <aadelimed@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
dotenv = "0.15"
base64 = "0.12"
